name: noise_app
description: Project that is checking noise levels around you.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  noise_meter: ^2.0.0

  audioplayers: ^0.17.4

  file_picker: ^2.1.6

  volume: ^1.0.1

  share: ^0.6.5+4

  flutter_email_sender: ^4.0.0

  flutter_local_notifications: ^4.0.1

  shared_preferences: ^0.5.12+4

  firebase_admob: ^0.11.0+1

  fluttertoast: ^7.1.8

  syncfusion_flutter_gauges: ^18.4.44

  syncfusion_flutter_charts: ^18.4.44+1

  android_alarm_manager: ^0.4.5+20

  google_mobile_ads: ^0.11.0+4

  system_shortcuts: ^1.0.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/sl.json
    - assets/audio/Bleep.mp3
    - assets/audio/Censor-beep-3.mp3
    - assets/audio/Foghorn.mp3
    - assets/audio/Grocery-Scanning.mp3
    - assets/audio/Snort-1.mp3
    - assets/audio/Snort-2.mp3
    - assets/audio/Snort-3.mp3
